spring.application.name=Tricol
spring.datasource.url=jdbc:postgresql://localhost:5432/tricol_db
spring.datasource.username=mohamed
spring.datasource.password=031203
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/tricol-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/tricol-realm/protocol/openid-connect/certs
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.com.tricol=DEBUG

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000